/**
 * Receipt Pro - Transfers Page
 * منطق هذه الصفحة فقط. الوظائف المشتركة موجودة في js/core/app.js
 * والبيانات موجودة في js/core/storage.js
 */

ReceiptPro.initLayout({active:'transfers',title:'التحويلات',subtitle:'انقل الأموال بين حساباتك وابحث في سجل التحويلات'});
const accounts=RPStore.getAccounts(),q=document.getElementById('transferSearch'),ff=document.getElementById('fromFilter'),tf=document.getElementById('toFilter'),fd=document.getElementById('transferFromDate'),td=document.getElementById('transferToDate');
const opts=accounts.map(a=>`<option value="${a.id}">${ReceiptPro.esc(a.name)}</option>`).join('');ff.innerHTML+=opts;tf.innerHTML+=opts;
[q,ff,tf,fd,td].forEach(x=>x.oninput=renderTransfers);document.getElementById('clearTransferFilters').onclick=()=>{q.value='';ff.value='all';tf.value='all';fd.value='';td.value='';renderTransfers()};document.getElementById('newTransfer').onclick=()=>openTransfer();renderTransfers();
function openTransfer(){const a=RPStore.getAccounts();if(a.length<2)return ReceiptPro.toast('تحتاج حسابين على الأقل لإجراء تحويل','warning');const fromDefault=new URLSearchParams(location.search).get('from')||'';ReceiptPro.modal(`<div class="modal"><div class="modal-head"><h3>تحويل جديد</h3><button class="icon-btn" onclick="ReceiptPro.closeModal()"><i class="fa-solid fa-xmark"></i></button></div><form id="transferForm"><div class="modal-body"><div class="form-grid"><div class="field"><label>من حساب</label><select id="fromAcc" required><option value="">اختر</option>${a.map(x=>`<option value="${x.id}" ${x.id===fromDefault?'selected':''}>${ReceiptPro.esc(x.name)} — ${ReceiptPro.fmt(RPStore.accountBalance(x.id))}</option>`).join('')}</select></div><div class="field"><label>إلى حساب</label><select id="toAcc" required><option value="">اختر</option>${a.map(x=>`<option value="${x.id}">${ReceiptPro.esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>المبلغ</label><input id="trAmount" type="number" step="0.01" min="0" required></div><div class="field"><label>التاريخ</label><input id="trDate" type="date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="field full"><label>ملاحظة</label><textarea id="trNote" placeholder="سبب التحويل أو أي ملاحظة"></textarea></div></div></div><div class="modal-foot"><button type="button" class="btn btn-secondary" onclick="ReceiptPro.closeModal()">إلغاء</button><button class="btn btn-primary"><i class="fa-solid fa-right-left"></i> تنفيذ التحويل</button></div></form></div>`);document.getElementById('transferForm').onsubmit=e=>{e.preventDefault();const f=document.getElementById('fromAcc').value,t=document.getElementById('toAcc').value,amount=Number(document.getElementById('trAmount').value);if(f===t)return ReceiptPro.toast('اختر حسابين مختلفين','error');if(!(amount>0))return ReceiptPro.toast('أدخل مبلغًا صحيحًا','error');if(amount>RPStore.accountBalance(f))return ReceiptPro.toast('الرصيد في الحساب المصدر غير كافٍ','error');RPStore.addTransfer({fromAccountId:f,toAccountId:t,amount,date:document.getElementById('trDate').value,note:document.getElementById('trNote').value});ReceiptPro.closeModal();ReceiptPro.toast('تم التحويل بنجاح');renderTransfers()}}
function renderTransfers(){let rows=RPStore.getTransfers();const text=q.value.trim().toLowerCase();rows=rows.filter(t=>(ff.value==='all'||t.fromAccountId===ff.value)&&(tf.value==='all'||t.toAccountId===tf.value)&&(!fd.value||t.date>=fd.value)&&(!td.value||t.date<=td.value)&&(!text||(RPStore.getTransferAccountName(t,'from')+' '+RPStore.getTransferAccountName(t,'to')+' '+(t.note||'')).toLowerCase().includes(text)));document.getElementById('transfersCountLabel').textContent=`${rows.length} تحويل`;const b=document.getElementById('transferBody');b.innerHTML=rows.length?rows.map(t=>`<tr><td>${ReceiptPro.esc(t.date)}</td><td>${ReceiptPro.esc(RPStore.getTransferAccountName(t,'from'))}</td><td>${ReceiptPro.esc(RPStore.getTransferAccountName(t,'to'))}</td><td><b>${ReceiptPro.fmt(t.amount)}</b></td><td>${ReceiptPro.esc(t.note||'-')}</td><td><div class="row-actions"><button class="delete" title="حذف" onclick="deleteTransfer('${t.id}')"><i class="fa-solid fa-trash-can"></i></button></div></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty"><div class="empty-icon"><i class="fa-solid fa-right-left"></i></div><h3>لا توجد تحويلات مطابقة</h3><p>غيّر البحث أو أنشئ تحويلًا جديدًا.</p></div></td></tr>'}
window.deleteTransfer=id=>{if(confirm('حذف التحويل؟')){RPStore.deleteTransfer(id);ReceiptPro.toast('تم حذف التحويل');renderTransfers()}}
