/**
 * Receipt Pro - Dashboard Page
 * منطق هذه الصفحة فقط. الوظائف المشتركة موجودة في js/core/app.js
 * والبيانات موجودة في js/core/storage.js
 */

ReceiptPro.initLayout({active:'dashboard',title:'لوحة التحكم',subtitle:'نظرة سريعة على أرصدتك وحركة النظام',actionHtml:'<a class="btn btn-primary" href="receipt.html"><i class="fa-solid fa-plus"></i> سند جديد</a>'});
const t=RPStore.totals();document.getElementById('totalBalance').textContent=ReceiptPro.fmt(t.balance);document.getElementById('accountsCount').textContent=t.accounts;document.getElementById('receiveTotal').textContent=ReceiptPro.fmt(t.receive);document.getElementById('payTotal').textContent=ReceiptPro.fmt(t.pay);document.getElementById('customersCount').textContent=t.customers;
const accs=RPStore.getAccounts().slice(0,5),al=document.getElementById('accountList');al.innerHTML=accs.length?accs.map(a=>`<a class="account-row" href="account-details.html?id=${a.id}"><span class="account-icon"><i class="fa-solid ${a.type==='cash'?'fa-money-bill-wave':'fa-building-columns'}"></i></span><div class="grow"><b>${ReceiptPro.esc(a.name)}</b><small>${ReceiptPro.esc(a.bankName|| (a.type==='cash'?'نقدي':'حساب مالي'))}</small></div><strong>${ReceiptPro.fmt(RPStore.accountBalance(a.id))}</strong></a>`).join(''):'<div class="empty-mini">لا توجد حسابات بعد. <a href="accounts.html" style="color:var(--primary)">أضف أول حساب</a></div>';
const rs=RPStore.getReceipts().slice(0,6),act=document.getElementById('activityList');act.innerHTML=rs.length?rs.map(r=>`<div class="activity-row"><span class="activity-icon" style="background:${r.type==='receive'?'#eaf8ef':'#fff0f0'};color:${r.type==='receive'?'var(--success)':'var(--danger)'}"><i class="fa-solid ${r.type==='receive'?'fa-arrow-down':'fa-arrow-up'}"></i></span><div class="grow"><b>${r.type==='receive'?'سند قبض':'سند صرف'} · ${ReceiptPro.esc(r.customerName||'بدون عميل')}</b><small>${ReceiptPro.esc(r.date)} · ${ReceiptPro.esc(RPStore.getReceiptAccountName(r))}</small></div><span class="amount ${r.type==='receive'?'text-success':'text-danger'}">${r.type==='receive'?'+':'-'}${ReceiptPro.fmt(r.amount)}</span></div>`).join(''):'<div class="empty-mini">لا توجد حركات مسجلة حتى الآن.</div>';
