/**
 * Receipt Pro - Reports Page
 * منطق هذه الصفحة فقط. الوظائف المشتركة موجودة في js/core/app.js
 * والبيانات موجودة في js/core/storage.js
 */

ReceiptPro.initLayout({active:'reports',title:'التقارير',subtitle:'حلّل القبض والصرف والأرصدة مع بحث وفلترة وتصدير Excel'});
const acc=document.getElementById('reportAccount'),q=document.getElementById('reportSearch'),from=document.getElementById('fromDate'),to=document.getElementById('toDate');
acc.innerHTML+=[...RPStore.getAccounts()].map(a=>`<option value="${a.id}">${ReceiptPro.esc(a.name)}</option>`).join('');
let c1,c2,reportType='all',currentRows=[];
[acc,q,from,to].forEach(x=>x.oninput=renderReport);
document.querySelectorAll('[data-report-type]').forEach(b=>b.onclick=()=>{reportType=b.dataset.reportType;document.querySelectorAll('[data-report-type]').forEach(x=>x.classList.toggle('active',x===b));renderReport()});
document.getElementById('clearReport').onclick=()=>{acc.value='all';q.value='';from.value='';to.value='';reportType='all';document.querySelectorAll('[data-report-type]').forEach(x=>x.classList.toggle('active',x.dataset.reportType==='all'));renderReport()};
document.getElementById('exportReportExcel').onclick=()=>ReceiptPro.exportExcel(currentRows,[{label:'التاريخ',value:'date'},{label:'رقم السند',value:'number'},{label:'النوع',value:r=>r.type==='receive'?'قبض':'صرف'},{label:'الحساب',value:r=>RPStore.getReceiptAccountName(r)},{label:'العميل / المستفيد',value:r=>r.customerName||''},{label:'المبلغ',value:r=>Number(r.amount)},{label:'البيان',value:r=>r.details||''}], 'receipt-pro-report');
renderReport();
function filtered(){const aid=acc.value,text=q.value.trim().toLowerCase();return RPStore.getReceipts().filter(r=>(aid==='all'||r.accountId===aid)&&(reportType==='all'||r.type===reportType)&&(!from.value||r.date>=from.value)&&(!to.value||r.date<=to.value)&&(!text||(r.number+' '+r.customerName+' '+r.details+' '+r.note+' '+RPStore.getReceiptAccountName(r)).toLowerCase().includes(text)))}
function renderReport(){const rows=currentRows=filtered();let receive=0,pay=0;rows.forEach(r=>r.type==='receive'?receive+=Number(r.amount):pay+=Number(r.amount));document.getElementById('rReceive').textContent=ReceiptPro.fmt(receive);document.getElementById('rPay').textContent=ReceiptPro.fmt(pay);document.getElementById('rNet').textContent=ReceiptPro.fmt(receive-pay);document.getElementById('rCount').textContent=rows.length;document.getElementById('reportBody').innerHTML=rows.length?rows.map(r=>`<tr><td>${ReceiptPro.esc(r.date)}</td><td><b>${ReceiptPro.esc(r.number)}</b></td><td><span class="pill ${r.type==='receive'?'green':'red'}">${r.type==='receive'?'قبض':'صرف'}</span></td><td>${ReceiptPro.esc(RPStore.getReceiptAccountName(r))}</td><td>${ReceiptPro.esc(r.customerName||'-')}</td><td class="${r.type==='receive'?'text-success':'text-danger'}"><b>${ReceiptPro.fmt(r.amount)}</b></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">لا توجد بيانات مطابقة للبحث.</div></td></tr>';drawCharts(rows)}
function drawCharts(rows){if(typeof Chart==='undefined')return;const grouped={};rows.forEach(r=>{grouped[r.date]??={receive:0,pay:0};grouped[r.date][r.type]+=Number(r.amount)});const dates=Object.keys(grouped).sort();c1?.destroy();c2?.destroy();c1=new Chart(document.getElementById('movementChart'),{type:'bar',data:{labels:dates,datasets:[{label:'قبض',data:dates.map(d=>grouped[d].receive)},{label:'صرف',data:dates.map(d=>grouped[d].pay)}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}});const accounts=RPStore.getAccounts();c2=new Chart(document.getElementById('accountsChart'),{type:'doughnut',data:{labels:accounts.map(a=>a.name),datasets:[{data:accounts.map(a=>Math.max(0,RPStore.accountBalance(a.id)))}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}})}
